const str = (key, size, required = true, array = false) => ({ key, type: "string", size, required, array });
const int = (key, required = true) => ({ key, type: "integer", required });
const bool = (key, required = true) => ({ key, type: "boolean", required });
const dt = (key, required = true) => ({ key, type: "datetime", required });

const commonCms = [
  int("sort_order"),
  bool("is_published"),
  dt("created_at"),
  dt("updated_at"),
];

export const database = {
  id: process.env.APPWRITE_DATABASE_ID?.trim() || "makabongwe_nonprod",
  name: "Makabongwe Non-Production",
  enabled: true,
};

export const tables = [
  {
    id: "cms_services",
    name: "CMS Services",
    permissions: [],
    rowSecurity: false,
    enabled: true,
    columns: [
      str("number", 2),
      str("slug", 180),
      str("title", 180),
      str("summary", 1500),
      str("items", 600, true, true),
      ...commonCms,
    ],
    indexes: [
      { key: "uniq_number", type: "unique", attributes: ["number"] },
      { key: "uniq_slug", type: "unique", attributes: ["slug"] },
      { key: "by_sort_order", type: "key", attributes: ["sort_order"] },
      { key: "by_published_sort", type: "key", attributes: ["is_published", "sort_order"] },
    ],
  },
  {
    id: "cms_programmes",
    name: "CMS Programmes",
    permissions: [],
    rowSecurity: false,
    enabled: true,
    columns: [
      str("slug", 180),
      str("title", 180),
      str("description", 1500),
      str("department", 180),
      str("duration", 120),
      str("delivery_mode", 120),
      str("location", 180),
      str("image_url", 2048, false),
      int("price_cents"),
      int("registration_fee_cents"),
      bool("is_available"),
      str("available_intake", 240, false),
      ...commonCms,
    ],
    indexes: [
      { key: "uniq_slug", type: "unique", attributes: ["slug"] },
      { key: "by_sort_order", type: "key", attributes: ["sort_order"] },
      { key: "by_publish_avail_sort", type: "key", attributes: ["is_published", "is_available", "sort_order"] },
    ],
  },
  {
    id: "cms_training_days",
    name: "CMS Training Days",
    permissions: [],
    rowSecurity: false,
    enabled: true,
    columns: [
      int("day_number"),
      str("title", 180),
      str("description", 1500),
      ...commonCms,
    ],
    indexes: [
      { key: "uniq_day_number", type: "unique", attributes: ["day_number"] },
      { key: "by_sort_order", type: "key", attributes: ["sort_order"] },
      { key: "by_published_sort", type: "key", attributes: ["is_published", "sort_order"] },
    ],
  },
  {
    id: "cms_qualifications",
    name: "CMS Qualifications",
    permissions: [],
    rowSecurity: false,
    enabled: true,
    columns: [
      str("code", 40),
      str("title", 220),
      str("nqf_level", 100),
      str("duration", 100),
      ...commonCms,
    ],
    indexes: [
      { key: "uniq_code", type: "unique", attributes: ["code"] },
      { key: "by_sort_order", type: "key", attributes: ["sort_order"] },
      { key: "by_published_sort", type: "key", attributes: ["is_published", "sort_order"] },
    ],
  },
  {
    id: "cms_delivery_steps",
    name: "CMS Delivery Steps",
    permissions: [],
    rowSecurity: false,
    enabled: true,
    columns: [
      str("slug", 180),
      str("title", 140),
      str("description", 1500),
      ...commonCms,
    ],
    indexes: [
      { key: "uniq_slug", type: "unique", attributes: ["slug"] },
      { key: "by_sort_order", type: "key", attributes: ["sort_order"] },
      { key: "by_published_sort", type: "key", attributes: ["is_published", "sort_order"] },
    ],
  },
  {
    id: "cms_values",
    name: "CMS Values",
    permissions: [],
    rowSecurity: false,
    enabled: true,
    columns: [
      str("slug", 180),
      str("title", 140),
      str("description", 1500),
      ...commonCms,
    ],
    indexes: [
      { key: "uniq_slug", type: "unique", attributes: ["slug"] },
      { key: "by_sort_order", type: "key", attributes: ["sort_order"] },
      { key: "by_published_sort", type: "key", attributes: ["is_published", "sort_order"] },
    ],
  },
  {
    id: "enquiries",
    name: "Enquiries",
    permissions: [],
    rowSecurity: false,
    enabled: true,
    columns: [
      dt("created_at"),
      str("status", 24),
      str("full_name", 120),
      str("organisation", 160, false),
      str("phone", 40),
      str("email", 254),
      str("service_programme", 160),
      str("programme_location", 160, false),
      int("estimated_learners", false),
      str("preferred_start_date", 10, false),
      str("message", 4000),
      str("source_page", 300),
      str("ip_hash", 64, false),
      str("user_agent", 300, false),
      str("notification_status", 24),
      str("notification_error", 300, false),
      dt("notified_at", false),
    ],
    indexes: [
      { key: "by_created_at", type: "key", attributes: ["created_at"] },
      { key: "by_email", type: "key", attributes: ["email"] },
      { key: "by_status_created", type: "key", attributes: ["status", "created_at"] },
      { key: "by_ip_created", type: "key", attributes: ["ip_hash", "created_at"] },
    ],
  },
  {
    id: "enrollments",
    name: "Enrollments",
    permissions: [],
    rowSecurity: false,
    enabled: true,
    columns: [
      str("course_id", 36),
      str("first_name", 120),
      str("last_name", 120),
      str("email", 254),
      str("phone", 40),
      str("id_passport_number", 120),
      str("date_of_birth", 10, false),
      str("address", 500),
      str("qualification", 240),
      str("preferred_intake", 240),
      str("notes", 2000, false),
      str("status", 32),
      str("payment_status", 24),
      dt("created_at"),
      dt("updated_at"),
      str("application_reference", 120),
      str("application_token_hash", 64, false),
      str("title", 40, false),
      str("middle_names", 180, false),
      str("nationality", 100, false),
      str("gender", 80, false),
      str("home_language", 100, false),
      str("alternate_phone", 40, false),
      str("city", 120, false),
      str("province", 120, false),
      str("postal_code", 20, false),
      str("last_institution", 240, false),
      int("year_completed", false),
      str("employment_status", 120, false),
      str("funding_source", 180, false),
      str("emergency_contact_name", 180, false),
      str("emergency_contact_relationship", 120, false),
      str("emergency_contact_phone", 40, false),
      bool("requires_support"),
      str("support_details", 2000, false),
      dt("popia_consent_at", false),
      dt("declaration_accepted_at", false),
      bool("marketing_consent"),
    ],
    indexes: [
      { key: "uniq_application_reference", type: "unique", attributes: ["application_reference"] },
      { key: "by_application_token", type: "key", attributes: ["application_token_hash"] },
      { key: "by_course", type: "key", attributes: ["course_id"] },
      { key: "by_email", type: "key", attributes: ["email"] },
      { key: "by_status", type: "key", attributes: ["status"] },
      { key: "by_payment_status", type: "key", attributes: ["payment_status"] },
    ],
  },
  {
    id: "payments",
    name: "Payments",
    permissions: [],
    rowSecurity: false,
    enabled: true,
    columns: [
      str("enrollment_id", 36),
      str("course_id", 36),
      str("paystack_reference", 120),
      int("amount"),
      str("currency", 3),
      str("status", 32),
      dt("paid_at", false),
      str("paystack_transaction_id", 120, false),
      str("customer_email", 254),
      str("raw_response", 8000, false),
      dt("created_at"),
      dt("updated_at"),
    ],
    indexes: [
      { key: "uniq_paystack_reference", type: "unique", attributes: ["paystack_reference"] },
      { key: "by_enrollment", type: "key", attributes: ["enrollment_id"] },
      { key: "by_course", type: "key", attributes: ["course_id"] },
      { key: "by_status", type: "key", attributes: ["status"] },
    ],
  },
  {
    id: "enrollment_documents",
    name: "Enrollment Documents",
    permissions: [],
    rowSecurity: false,
    enabled: true,
    columns: [
      str("enrollment_id", 36),
      str("document_type", 40),
      str("storage_bucket", 64),
      str("storage_path", 500),
      str("original_filename", 255),
      str("mime_type", 80),
      int("file_size_bytes"),
      str("status", 32),
      dt("uploaded_at", false),
      dt("verified_at", false),
      str("rejection_reason", 1500, false),
      dt("created_at"),
      dt("updated_at"),
    ],
    indexes: [
      { key: "uniq_storage_path", type: "unique", attributes: ["storage_path"] },
      { key: "uniq_enrollment_doc_type", type: "unique", attributes: ["enrollment_id", "document_type"] },
      { key: "by_enrollment", type: "key", attributes: ["enrollment_id"] },
      { key: "by_status", type: "key", attributes: ["status"] },
    ],
  },
];

export const storageBucket = {
  id: "enrollment-documents",
  name: "Enrollment Documents",
  permissions: [],
  fileSecurity: true,
  enabled: true,
  maximumFileSize: 10 * 1024 * 1024,
  allowedFileExtensions: ["pdf", "jpg", "jpeg", "png"],
  compression: "none",
  encryption: true,
  antivirus: false,
  transformations: false,
};

export const cmsTableIds = [
  "cms_delivery_steps",
  "cms_programmes",
  "cms_qualifications",
  "cms_services",
  "cms_training_days",
  "cms_values",
];

export const expectedCmsCounts = {
  cms_delivery_steps: 7,
  cms_programmes: 5,
  cms_qualifications: 5,
  cms_services: 6,
  cms_training_days: 10,
  cms_values: 6,
};
