-- Editable website content for Makabongwe Training Institute.
-- The public site reads these rows through its server-only Supabase connection.

create table public.cms_services (
  id bigint generated by default as identity primary key,
  number text not null unique check (number ~ '^[0-9]{2}$'),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null check (char_length(title) between 2 and 160),
  summary text not null check (char_length(summary) between 10 and 1000),
  items text[] not null default '{}',
  sort_order integer not null default 0 check (sort_order >= 0),
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.cms_programmes (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null check (char_length(title) between 2 and 160),
  description text not null check (char_length(description) between 10 and 1000),
  sort_order integer not null default 0 check (sort_order >= 0),
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.cms_training_days (
  id bigint generated by default as identity primary key,
  day_number integer not null unique check (day_number between 1 and 365),
  title text not null check (char_length(title) between 2 and 160),
  description text not null check (char_length(description) between 10 and 1000),
  sort_order integer not null default 0 check (sort_order >= 0),
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.cms_qualifications (
  id bigint generated by default as identity primary key,
  code text not null unique check (char_length(code) between 2 and 40),
  title text not null check (char_length(title) between 2 and 200),
  nqf_level text not null check (char_length(nqf_level) between 2 and 80),
  duration text not null check (char_length(duration) between 2 and 80),
  sort_order integer not null default 0 check (sort_order >= 0),
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.cms_delivery_steps (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null check (char_length(title) between 2 and 120),
  description text not null check (char_length(description) between 10 and 1000),
  sort_order integer not null default 0 check (sort_order >= 0),
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.cms_values (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null check (char_length(title) between 2 and 120),
  description text not null check (char_length(description) between 10 and 1000),
  sort_order integer not null default 0 check (sort_order >= 0),
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.cms_services is 'Service cards and detail content displayed on the website.';
comment on table public.cms_programmes is 'Packaged programmes displayed on the programmes page.';
comment on table public.cms_training_days is 'Day-by-day content for the Azibuye Emasisweni practical journey.';
comment on table public.cms_qualifications is 'Accredited qualifications displayed on the AgriSETA and programmes pages.';
comment on table public.cms_delivery_steps is 'Delivery stages shown on the homepage and partner page.';
comment on table public.cms_values is 'Makabongwe values displayed on the about page.';

alter table public.cms_services enable row level security;
alter table public.cms_programmes enable row level security;
alter table public.cms_training_days enable row level security;
alter table public.cms_qualifications enable row level security;
alter table public.cms_delivery_steps enable row level security;
alter table public.cms_values enable row level security;

-- Editing happens in the authenticated Supabase dashboard. Website reads are
-- performed only by the Next.js backend; no CMS table is directly public.
revoke all on table public.cms_services, public.cms_programmes,
  public.cms_training_days, public.cms_qualifications,
  public.cms_delivery_steps, public.cms_values from anon, authenticated;

grant select, insert, update, delete on table public.cms_services,
  public.cms_programmes, public.cms_training_days, public.cms_qualifications,
  public.cms_delivery_steps, public.cms_values to service_role;

revoke all on sequence public.cms_services_id_seq,
  public.cms_programmes_id_seq, public.cms_training_days_id_seq,
  public.cms_qualifications_id_seq, public.cms_delivery_steps_id_seq,
  public.cms_values_id_seq from anon, authenticated;

grant usage, select on sequence public.cms_services_id_seq,
  public.cms_programmes_id_seq, public.cms_training_days_id_seq,
  public.cms_qualifications_id_seq, public.cms_delivery_steps_id_seq,
  public.cms_values_id_seq to service_role;

insert into public.cms_services
  (number, slug, title, summary, items, sort_order)
values
  ('01', 'agricultural-skills-development', 'Agricultural Skills Development',
   'Practical agricultural learning that builds skills, confidence and productive capability—from beginner workshops to structured accredited programmes.',
   array['Poultry, animal production, plant production and horticulture streams within approved scope', 'Farm management, agricultural health and safety, stock control and recordkeeping', 'Training-needs analysis, learner orientation and practical demonstrations', 'Accredited learning and non-credit-bearing practical workshops'], 1),
  ('02', 'poultry-production-enterprise-support', 'Poultry Production & Enterprise Support',
   'End-to-end poultry support—from housing and feeding to records, enterprise planning, incubation and market readiness.',
   array['Broiler, layer and dual-purpose chicken training', 'Housing, equipment, feeding and flock-management guidance', 'Biosecurity, hygiene and disease-prevention awareness', 'Costing, pricing, budgeting, sales and starter-flock programme design'], 2),
  ('03', 'food-security-sustainable-agriculture', 'Food Security & Sustainable Agriculture',
   'Sustainable food gardens and community agriculture projects that strengthen nutrition, practical skills and local resilience.',
   array['Household, community, school, church and ECD food gardens', 'Horticulture, seedlings and seasonal planting programmes', 'Soil preparation, composting, water-use and maintenance planning', 'Starter packs linked to training and follow-up support'], 3),
  ('04', 'youth-women-community-empowerment', 'Youth, Women & Community Empowerment',
   'Inclusive programmes that help youth, women, families and communities build skills, livelihoods and enterprises.',
   array['Youth agricultural entrepreneurship programmes', 'Women-in-agriculture and family livelihood initiatives', 'Inclusive opportunities for persons with disabilities', 'Cooperative development, work readiness and financial discipline'], 4),
  ('05', 'enterprise-incubation-mentorship', 'Enterprise Incubation & Mentorship',
   'Structured business support that helps emerging farmers plan, manage, market and grow viable agricultural enterprises.',
   array['Business models, budgets, cash-flow, costing and pricing', 'Production records, stock control and financial discipline', 'Branding, packaging, customer identification and selling', 'Site visits, problem-solving, funding and market readiness'], 5),
  ('06', 'programme-implementation-consultancy', 'Programme Implementation & Consultancy',
   'Reliable end-to-end programme delivery for institutions that need planning, training, implementation, monitoring and impact reporting.',
   array['Needs assessments, feasibility studies and programme design', 'Beneficiary recruitment, screening and administration', 'Project logistics, starter-pack coordination and implementation', 'Monitoring, evidence management, reporting and sustainability planning'], 6);

insert into public.cms_programmes (slug, title, description, sort_order)
values
  ('poultry-starter-workshop', 'Poultry Starter Workshop', 'A practical introduction for aspiring backyard and small-scale poultry farmers.', 1),
  ('broiler-business-bootcamp', 'Broiler Business Bootcamp', 'A focused production and business programme covering cycle planning, costs, records and selling.', 2),
  ('school-food-garden-package', 'School Food Garden Package', 'Garden setup, learner participation, maintenance planning and educator support.', 3),
  ('farm-cooperative-upskilling', 'Farm & Cooperative Upskilling', 'Custom practical training for workers, cooperatives and emerging producers.', 4),
  ('100-youth-poultry-entrepreneurs', '100 Youth Poultry Entrepreneurs', 'A structured enterprise model combining learning, demonstration, incubation and mentorship.', 5);

insert into public.cms_training_days (day_number, title, description, sort_order)
values
  (1, 'Orientation & opportunity', 'Understand expectations, poultry value chains and personal goals.', 1),
  (2, 'Breeds & production systems', 'Choose suitable broiler, layer or dual-purpose approaches.', 2),
  (3, 'Chick care & flock management', 'Apply basic brooding, handling and daily care practices.', 3),
  (4, 'Housing & equipment', 'Plan safe, ventilated and affordable poultry structures.', 4),
  (5, 'Feed & water management', 'Use feeding systems responsibly and track consumption.', 5),
  (6, 'Breeding & flock growth', 'Understand reproduction, selection and growth planning.', 6),
  (7, 'Biosecurity & prevention', 'Implement hygiene, access-control and prevention routines.', 7),
  (8, 'Stock & production records', 'Track flock numbers, mortality, feed and production.', 8),
  (9, 'Financial management', 'Budget, record expenses, calculate sales and understand profit.', 9),
  (10, 'Business plan & mentorship', 'Complete an action plan and enter the support pathway.', 10);

insert into public.cms_qualifications (code, title, nqf_level, duration, sort_order)
values
  ('48976', 'National Certificate: Animal Production', 'NQF Level 2', '12 months', 1),
  ('49048', 'National Certificate: Animal Production', 'NQF Level 3', '12 months', 2),
  ('49052', 'National Certificate: Plant Production', 'NQF Level 3', '12 months', 3),
  ('49582', 'National Certificate: Poultry Production', 'NQF Level 2', '12 months', 4),
  ('66589', 'National Certificate: Horticulture', 'NQF Level 2', '12 months', 5);

insert into public.cms_delivery_steps (slug, title, description, sort_order)
values
  ('diagnose', 'Diagnose', 'Confirm objectives, beneficiaries, location and expected outcomes.', 1),
  ('design', 'Design', 'Build the scope, budget, learning plan and reporting framework.', 2),
  ('mobilise', 'Mobilise', 'Recruit learners and prepare people, venues, materials and logistics.', 3),
  ('deliver', 'Deliver', 'Facilitate learning, demonstrations, assessments and learner support.', 4),
  ('implement', 'Implement', 'Coordinate starter inputs, setup and enterprise action plans.', 5),
  ('mentor', 'Mentor', 'Provide structured technical and business follow-up.', 6),
  ('measure', 'Measure', 'Track progress, risks and outcomes with evidence-based reporting.', 7);

insert into public.cms_values (slug, title, description, sort_order)
values
  ('practical-impact', 'Practical impact', 'Skills that can be applied in real production and business environments.', 1),
  ('integrity', 'Integrity', 'Honest communication, responsible resources and accurate reporting.', 2),
  ('inclusion', 'Inclusion', 'Opportunity for youth, women, persons with disabilities and underserved communities.', 3),
  ('excellence', 'Excellence', 'Professional standards in training, quality assurance and learner support.', 4),
  ('sustainability', 'Sustainability', 'Responsible production, reinvestment and long-term enterprise growth.', 5),
  ('partnership', 'Partnership', 'Collaboration with communities, institutions, government and industry.', 6);
